// ============================================================================
// Analytics Package - Barrel Export
// ============================================================================

export { EventTracker } from './core/event-tracker';
export { FunnelAnalyzer } from './core/funnel-analyzer';
export { ABTestingEngine } from './core/ab-testing';
export { CohortAnalyzer } from './core/cohort-analyzer';
export { AttributionEngine } from './core/attribution';
export { RealtimeDashboard } from './core/realtime-dashboard';
export { PredictiveAnalytics } from './core/predictive-analytics';
export { AttributionModel } from './core/attribution-model';
export { FunnelOptimizer } from './core/funnel-optimizer';
export { UserSegmentation } from './core/user-segmentation';
export { EventPipeline } from './core/event-pipeline';

export type {
  AnalyticsEvent,
  EventType,
  EventContext,
  EventMetadata,
  PageViewEvent,
  ClickEvent,
  ScrollEvent,
  PageInfo,
  DeviceInfo,
  CampaignInfo,
  GeoInfo,
  FunnelStep,
  FunnelCondition,
  FunnelDefinition,
  FunnelConversionData,
  StepConversion,
  ABTest,
  ABTestVariant,
  ABTestStatus,
  ABTestResult,
  VariantResult,
  CohortDefinition,
  CohortGroupBy,
  CohortFilter,
  CohortMetrics,
  PeriodMetric,
  AttributionModelType,
  AttributionTouch,
  AttributionReport,
  ChannelAttribution,
  DashboardMetrics,
  PageMetric,
  EventMetric,
  EventBatch,
  EventTrackerConfig,
  TimeSeriesPoint,
  MetricsSubscriber,
  AnalyticsConfig,
  ForecastConfig,
  SeasonalModel,
  ForecastResult,
  ConfidenceInterval,
  DecompositionResult,
  WhatIfScenario,
  ScenarioResult,
  Touchpoint,
  TouchpointJourney,
  AttributionResultEntry,
  AttributionAnalysisResult,
  AdvancedAttributionModelType,
  ShapleyConfig,
  ChannelInteraction,
  DeviceMatch,
  OptimizedFunnelDefinition,
  OptimizedFunnelStep,
  FunnelComputationResult,
  StepResult,
  DropOffAnalysis,
  SegmentComparisonResult,
  MarkovTransition,
  FunnelEvent,
  SegmentDefinition,
  SegmentCriteria,
  SegmentRule,
  RFMScore,
  ClusterConfig,
  Centroid,
  ClusterAssignment,
  LifecycleStage,
  UserLifecycleData,
  SegmentOverlap,
  SegmentGrowth,
  EventSchema,
  SchemaField,
  ValidationRule,
  SessionConfig,
  PipelineEventBatch,
  PipelineEvent,
  WatermarkConfig,
  SamplingConfig,
  Session,
  PipelineMetrics,
  EnrichmentFunction,
} from './types';
