// ============================================================================
// QuantTube - Chapters Service
// Video chapters, auto-generation, scene detection, timestamp validation
// ============================================================================

interface Chapter {
  id: string;
  videoId: string;
  timestamp: number;
  endTimestamp: number;
  title: string;
  thumbnailUrl: string;
  order: number;
  isAutoGenerated: boolean;
  confidence?: number;
  createdAt: string;
  updatedAt: string;
}

interface SceneChange {
  timestamp: number;
  frameDifference: number;
  suggestedTitle: string;
  confidence: number;
  type: 'hard_cut' | 'dissolve' | 'fade' | 'wipe' | 'topic_change';
}

interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
  speaker?: string;
  topics: string[];
}

interface AutoGenerateResult {
  videoId: string;
  chapters: Chapter[];
  confidence: number;
  method: 'transcript' | 'scene_detection' | 'hybrid';
  processingTimeMs: number;
}

class ChaptersService {
  private chapters: Map<string, Chapter[]> = new Map();
  private sceneCache: Map<string, SceneChange[]> = new Map();
  private transcripts: Map<string, TranscriptSegment[]> = new Map();
  private counter: number = 0;

  private generateId(): string {
    return `chap_${Date.now().toString(36)}_${(++this.counter).toString(36)}`;
  }

  async createChapter(videoId: string, timestamp: number, title: string, endTimestamp?: number): Promise<Chapter> {
    const existing = this.chapters.get(videoId) || [];
    const validationResult = this.validateTimestamp(videoId, timestamp, existing);
    if (!validationResult.valid) {
      throw new Error(`Invalid timestamp: ${validationResult.reason}`);
    }

    const chapter: Chapter = {
      id: this.generateId(),
      videoId,
      timestamp,
      endTimestamp: endTimestamp || timestamp + 30,
      title: title.trim().substring(0, 100),
      thumbnailUrl: `https://cdn.quant.tube/thumbs/${videoId}/${timestamp}.jpg`,
      order: existing.length,
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    existing.push(chapter);
    existing.sort((a, b) => a.timestamp - b.timestamp);
    existing.forEach((ch, idx) => { ch.order = idx; });
    this.chapters.set(videoId, existing);

    return chapter;
  }

  async deleteChapter(videoId: string, chapterId: string): Promise<boolean> {
    const existing = this.chapters.get(videoId);
    if (!existing) return false;

    const idx = existing.findIndex(ch => ch.id === chapterId);
    if (idx === -1) return false;

    existing.splice(idx, 1);
    existing.forEach((ch, i) => { ch.order = i; });
    this.chapters.set(videoId, existing);
    return true;
  }

  async autoGenerate(videoId: string): Promise<AutoGenerateResult> {
    const startTime = Date.now();
    const transcript = this.transcripts.get(videoId) || this.generateMockTranscript(videoId);
    const sceneChanges = await this.detectSceneChanges(videoId);

    const topicClusters = this.clusterByTopics(transcript);
    const sceneChapters = this.chaptersFromScenes(videoId, sceneChanges);
    const topicChapters = this.chaptersFromTopics(videoId, topicClusters);

    const merged = this.mergeChapterSuggestions(videoId, sceneChapters, topicChapters);
    const existing = this.chapters.get(videoId) || [];
    const newChapters = merged.filter(ch => !existing.some(e => Math.abs(e.timestamp - ch.timestamp) < 5));

    const allChapters = [...existing, ...newChapters].sort((a, b) => a.timestamp - b.timestamp);
    allChapters.forEach((ch, idx) => { ch.order = idx; });
    this.chapters.set(videoId, allChapters);

    const avgConfidence = merged.reduce((sum, ch) => sum + (ch.confidence || 0.7), 0) / (merged.length || 1);

    return {
      videoId,
      chapters: allChapters,
      confidence: Math.round(avgConfidence * 100) / 100,
      method: 'hybrid',
      processingTimeMs: Date.now() - startTime,
    };
  }

  private generateMockTranscript(videoId: string): TranscriptSegment[] {
    const duration = 300 + Math.floor(Math.random() * 600);
    const segments: TranscriptSegment[] = [];
    const topics = ['introduction', 'setup', 'main_content', 'demonstration', 'results', 'conclusion', 'outro'];
    let currentTime = 0;

    while (currentTime < duration) {
      const segLength = 10 + Math.floor(Math.random() * 20);
      const topicIdx = Math.min(topics.length - 1, Math.floor((currentTime / duration) * topics.length));
      segments.push({
        start: currentTime,
        end: Math.min(currentTime + segLength, duration),
        text: `Segment at ${currentTime}s discussing ${topics[topicIdx]}`,
        topics: [topics[topicIdx]],
      });
      currentTime += segLength;
    }

    this.transcripts.set(videoId, segments);
    return segments;
  }

  private clusterByTopics(segments: TranscriptSegment[]): { topic: string; startTime: number; endTime: number }[] {
    const clusters: { topic: string; startTime: number; endTime: number }[] = [];
    let currentTopic = '';
    let clusterStart = 0;

    for (const seg of segments) {
      const mainTopic = seg.topics[0] || 'general';
      if (mainTopic !== currentTopic) {
        if (currentTopic) {
          clusters.push({ topic: currentTopic, startTime: clusterStart, endTime: seg.start });
        }
        currentTopic = mainTopic;
        clusterStart = seg.start;
      }
    }
    if (currentTopic && segments.length > 0) {
      clusters.push({ topic: currentTopic, startTime: clusterStart, endTime: segments[segments.length - 1].end });
    }

    return clusters;
  }

  private chaptersFromScenes(videoId: string, scenes: SceneChange[]): Chapter[] {
    return scenes
      .filter(s => s.confidence > 0.6 && s.type === 'hard_cut')
      .map((scene, idx) => ({
        id: this.generateId(),
        videoId,
        timestamp: scene.timestamp,
        endTimestamp: scene.timestamp + 30,
        title: scene.suggestedTitle,
        thumbnailUrl: `https://cdn.quant.tube/thumbs/${videoId}/${scene.timestamp}.jpg`,
        order: idx,
        isAutoGenerated: true,
        confidence: scene.confidence,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }));
  }

  private chaptersFromTopics(videoId: string, clusters: { topic: string; startTime: number; endTime: number }[]): Chapter[] {
    return clusters.map((cluster, idx) => ({
      id: this.generateId(),
      videoId,
      timestamp: cluster.startTime,
      endTimestamp: cluster.endTime,
      title: cluster.topic.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      thumbnailUrl: `https://cdn.quant.tube/thumbs/${videoId}/${cluster.startTime}.jpg`,
      order: idx,
      isAutoGenerated: true,
      confidence: 0.75,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }));
  }

  private mergeChapterSuggestions(videoId: string, sceneChapters: Chapter[], topicChapters: Chapter[]): Chapter[] {
    const all = [...sceneChapters, ...topicChapters].sort((a, b) => a.timestamp - b.timestamp);
    const merged: Chapter[] = [];
    for (const ch of all) {
      const last = merged[merged.length - 1];
      if (!last || ch.timestamp - last.timestamp > 15) {
        merged.push(ch);
      } else if ((ch.confidence || 0) > (last.confidence || 0)) {
        merged[merged.length - 1] = ch;
      }
    }
    return merged;
  }

  async reorder(videoId: string, chapterIds: string[]): Promise<Chapter[]> {
    const existing = this.chapters.get(videoId);
    if (!existing) throw new Error('No chapters found for video');

    const reordered: Chapter[] = [];
    for (const id of chapterIds) {
      const chapter = existing.find(ch => ch.id === id);
      if (chapter) {
        chapter.order = reordered.length;
        chapter.updatedAt = new Date().toISOString();
        reordered.push(chapter);
      }
    }

    this.chapters.set(videoId, reordered);
    return reordered;
  }

  async getChapters(videoId: string): Promise<Chapter[]> {
    return this.chapters.get(videoId) || [];
  }

  validateTimestamp(videoId: string, timestamp: number, existing: Chapter[]): { valid: boolean; reason?: string } {
    if (timestamp < 0) return { valid: false, reason: 'Timestamp cannot be negative' };
    if (timestamp > 86400) return { valid: false, reason: 'Timestamp exceeds maximum video length' };
    const tooClose = existing.find(ch => Math.abs(ch.timestamp - timestamp) < 5);
    if (tooClose) return { valid: false, reason: `Too close to existing chapter at ${tooClose.timestamp}s` };
    return { valid: true };
  }

  async detectSceneChanges(videoId: string): Promise<SceneChange[]> {
    const cached = this.sceneCache.get(videoId);
    if (cached) return cached;

    const duration = 300 + Math.floor(Math.random() * 600);
    const numScenes = 5 + Math.floor(Math.random() * 15);
    const scenes: SceneChange[] = [];
    const types: SceneChange['type'][] = ['hard_cut', 'dissolve', 'fade', 'wipe', 'topic_change'];
    const titles = ['Introduction', 'Getting Started', 'Deep Dive', 'Key Point', 'Example', 'Summary', 'Transition', 'New Section', 'Demo', 'Results'];

    for (let i = 0; i < numScenes; i++) {
      const timestamp = Math.floor((duration / numScenes) * i + Math.random() * (duration / numScenes / 2));
      const frameDiff = 0.3 + Math.random() * 0.7;
      scenes.push({
        timestamp,
        frameDifference: Math.round(frameDiff * 1000) / 1000,
        suggestedTitle: titles[i % titles.length],
        confidence: 0.5 + Math.random() * 0.5,
        type: types[Math.floor(Math.random() * types.length)],
      });
    }

    scenes.sort((a, b) => a.timestamp - b.timestamp);
    this.sceneCache.set(videoId, scenes);
    return scenes;
  }
}

export const chaptersService = new ChaptersService();
export { ChaptersService };
