// ============================================================================
// Admin & Operations Package - Barrel Export
// ============================================================================

export { AdminDashboard } from './core/admin-dashboard';
export { UserManagement } from './core/user-management';
export { ContentModerationQueue } from './core/content-moderation';
export { SystemHealthMonitor } from './core/system-health';
export { FeatureFlagService } from './core/feature-flags';
export { LiveConfigManager } from './core/config-manager';
export { IncidentManager } from './core/incident-manager';
export { DeploymentManager } from './core/deployment-manager';
export { MigrationRunner } from './core/migration-runner';
export { JobMonitor } from './core/job-monitor';
export { AlertEngine } from './core/alert-engine';
export { AuditTrail } from './core/audit-trail';
export { RevenueDashboard } from './core/revenue-dashboard';
export { SupportTicketSystem } from './core/support-tickets';

export type {
  AdminUser,
  AdminRole,
  AdminPermission,
  RBACPolicy,
  PolicyRestriction,
  UserSearchQuery,
  UserStatus,
  UserSearchResult,
  UserProfile,
  UserAction,
  UserActionType,
  BanConfig,
  SuspensionConfig,
  ImpersonationSession,
  ContentModerationItem,
  ContentType,
  ModerationAction,
  ModerationActionType,
  ModerationPriority,
  ModerationStatus,
  ModerationStats,
  ReviewerStats,
  AppealRequest,
  AppealStatus,
  ReviewerAssignment,
  SystemHealth,
  HealthStatus,
  ServiceStatus,
  UptimeRecord,
  ErrorRateMetric,
  TrendDirection,
  LatencyMetric,
  HealthCheck,
  DependencyStatus,
  DependencyType,
  FeatureFlag,
  FlagType,
  RolloutConfig,
  TargetingRule,
  TargetingOperator,
  ABVariant,
  ABTestConfig,
  FlagEvaluation,
  EvaluationReason,
  GradualRollout,
  RolloutStage,
  LiveConfig,
  ConfigValueType,
  ConfigEntry,
  ConfigVersion,
  ConfigChange,
  ConfigValidationRule,
  EnvironmentConfig,
  SecretConfig,
  Incident,
  IncidentSeverity,
  IncidentStatus,
  StatusUpdate,
  Responder,
  ResponderRole,
  PostMortem,
  PostMortemSection,
  Deployment,
  DeploymentStrategy,
  DeploymentStatus,
  CanaryConfig,
  MetricsGate,
  RollbackInfo,
  ApprovalWorkflow,
  ApprovalRecord,
  Migration,
  MigrationDirection,
  MigrationStatus,
  MigrationFile,
  BatchResult,
  BackgroundJob,
  JobStatus,
  JobQueue,
  QueueStats,
  JobRetry,
  JobHistory,
  AlertRule,
  AlertCondition,
  AlertSeverity,
  AlertChannel,
  AlertChannelType,
  AlertStatus,
  AlertState,
  AnomalyConfig,
  ZScoreResult,
  AuditEntry,
  ActorType,
  AuditAction,
  AuditFilter,
  AuditChain,
  AuditExport,
  RevenueSnapshot,
  SubscriptionMetric,
  RefundMetric,
  RevenueForecast,
  RevenueBySegment,
  SupportTicket,
  TicketStatus,
  TicketPriority,
  TicketCategory,
  TicketSLA,
  TicketResponse,
  EscalationRule,
  EscalationCondition,
  EscalationAction,
  CSATScore,
} from './types';
