// ============================================================================
// QuantNeon - Accessibility Service
// Alt text, auto-generation, sensitivity screens, content warnings
// ============================================================================

interface AltTextEntry {
  id: string;
  mediaId: string;
  text: string;
  isAutoGenerated: boolean;
  confidence?: number;
  language: string;
  createdAt: string;
  updatedAt: string;
}

interface SensitivityScreen {
  id: string;
  postId: string;
  type: 'graphic_violence' | 'nudity' | 'sensitive_content' | 'disturbing' | 'flashing_lights' | 'spoiler';
  label: string;
  customMessage?: string;
  createdAt: string;
}

interface ContentWarning {
  id: string;
  postId: string;
  warning: string;
  category: 'trigger_warning' | 'spoiler' | 'mature' | 'medical' | 'political' | 'custom';
  severity: 'low' | 'medium' | 'high';
  createdAt: string;
}

interface AccessibilityStats {
  accountId: string;
  totalMedia: number;
  withAltText: number;
  withAutoAlt: number;
  withManualAlt: number;
  coveragePercentage: number;
  avgAltTextLength: number;
  sensitivityScreens: number;
  contentWarnings: number;
  accessibilityScore: number;
  recommendations: string[];
}

interface AutoAltResult {
  mediaId: string;
  generatedText: string;
  confidence: number;
  detectedObjects: { label: string; confidence: number; boundingBox: { x: number; y: number; w: number; h: number } }[];
  detectedText: string[];
  dominantColors: string[];
  sceneType: string;
}

class AccessibilityService {
  private altTexts: Map<string, AltTextEntry> = new Map();
  private sensitivityScreens: Map<string, SensitivityScreen> = new Map();
  private contentWarnings: Map<string, ContentWarning> = new Map();
  private userMedia: Map<string, string[]> = new Map();
  private counter: number = 0;

  private genId(prefix: string): string {
    return `${prefix}_${Date.now().toString(36)}_${(++this.counter).toString(36)}`;
  }

  async addAltText(mediaId: string, text: string, language: string = 'en'): Promise<AltTextEntry> {
    if (text.length < 5) throw new Error('Alt text must be at least 5 characters');
    if (text.length > 1000) throw new Error('Alt text cannot exceed 1000 characters');

    const existing = this.altTexts.get(mediaId);
    if (existing) {
      existing.text = text.trim();
      existing.isAutoGenerated = false;
      existing.language = language;
      existing.updatedAt = new Date().toISOString();
      return existing;
    }

    const entry: AltTextEntry = {
      id: this.genId('alt'),
      mediaId,
      text: text.trim(),
      isAutoGenerated: false,
      language,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.altTexts.set(mediaId, entry);
    return entry;
  }

  async autoGenerateAlt(mediaId: string): Promise<AutoAltResult> {
    const objects = [
      { label: 'person', confidence: 0.95 },
      { label: 'building', confidence: 0.88 },
      { label: 'sky', confidence: 0.92 },
      { label: 'tree', confidence: 0.85 },
      { label: 'car', confidence: 0.78 },
      { label: 'food', confidence: 0.82 },
      { label: 'animal', confidence: 0.90 },
    ];

    const numObjects = 2 + Math.floor(Math.random() * 4);
    const shuffled = objects.sort(() => Math.random() - 0.5).slice(0, numObjects);
    const detectedObjects = shuffled.map(obj => ({
      label: obj.label,
      confidence: obj.confidence * (0.9 + Math.random() * 0.1),
      boundingBox: { x: Math.random() * 0.5, y: Math.random() * 0.5, w: 0.2 + Math.random() * 0.3, h: 0.2 + Math.random() * 0.3 },
    }));

    const sceneTypes = ['outdoor', 'indoor', 'landscape', 'portrait', 'food', 'urban', 'nature'];
    const sceneType = sceneTypes[Math.floor(Math.random() * sceneTypes.length)];
    const dominantColors = ['#336699', '#CC6633', '#669933', '#993366', '#FFCC00'].sort(() => Math.random() - 0.5).slice(0, 3);

    const objectNames = detectedObjects.map(o => o.label).join(', ');
    const generatedText = `A ${sceneType} scene featuring ${objectNames}. The image contains ${detectedObjects.length} main elements with ${dominantColors.length > 2 ? 'vibrant' : 'muted'} colors.`;
    const confidence = detectedObjects.reduce((s, o) => s + o.confidence, 0) / detectedObjects.length;

    const altEntry: AltTextEntry = {
      id: this.genId('alt'),
      mediaId,
      text: generatedText,
      isAutoGenerated: true,
      confidence,
      language: 'en',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.altTexts.set(mediaId, altEntry);

    return { mediaId, generatedText, confidence, detectedObjects, detectedText: [], dominantColors, sceneType };
  }

  async setSensitivityScreen(postId: string, type: SensitivityScreen['type'], customMessage?: string): Promise<SensitivityScreen> {
    const labels: Record<SensitivityScreen['type'], string> = {
      graphic_violence: 'This content contains graphic violence',
      nudity: 'This content contains nudity',
      sensitive_content: 'This content may be sensitive',
      disturbing: 'This content may be disturbing to some viewers',
      flashing_lights: 'This content contains flashing lights',
      spoiler: 'This content contains spoilers',
    };

    const screen: SensitivityScreen = {
      id: this.genId('sens'),
      postId,
      type,
      label: customMessage || labels[type],
      customMessage,
      createdAt: new Date().toISOString(),
    };

    this.sensitivityScreens.set(postId, screen);
    return screen;
  }

  async setContentWarning(postId: string, warning: string, category: ContentWarning['category'] = 'custom', severity: ContentWarning['severity'] = 'medium'): Promise<ContentWarning> {
    if (warning.length < 3 || warning.length > 200) throw new Error('Warning must be 3-200 characters');

    const cw: ContentWarning = {
      id: this.genId('cw'),
      postId,
      warning: warning.trim(),
      category,
      severity,
      createdAt: new Date().toISOString(),
    };

    this.contentWarnings.set(postId, cw);
    return cw;
  }

  async getAccessibilityStats(accountId: string): Promise<AccessibilityStats> {
    const mediaIds = this.userMedia.get(accountId) || [];
    const totalMedia = mediaIds.length || 50;
    const withAlt = mediaIds.filter(id => this.altTexts.has(id)).length;
    const autoAlts = mediaIds.filter(id => { const a = this.altTexts.get(id); return a?.isAutoGenerated; }).length;
    const manualAlts = withAlt - autoAlts;
    const coveragePercentage = totalMedia > 0 ? Math.round((withAlt / totalMedia) * 10000) / 100 : 0;

    const altEntries = Array.from(this.altTexts.values());
    const avgLength = altEntries.length > 0 ? altEntries.reduce((s, a) => s + a.text.length, 0) / altEntries.length : 0;

    const screensCount = Array.from(this.sensitivityScreens.values()).length;
    const warningsCount = Array.from(this.contentWarnings.values()).length;

    const accessibilityScore = Math.min(100, Math.round(coveragePercentage * 0.6 + (avgLength > 50 ? 20 : avgLength > 20 ? 10 : 0) + (screensCount > 0 ? 10 : 0) + (warningsCount > 0 ? 10 : 0)));

    const recommendations: string[] = [];
    if (coveragePercentage < 80) recommendations.push('Add alt text to more images for better accessibility');
    if (avgLength < 30) recommendations.push('Write more descriptive alt text (aim for 50+ characters)');
    if (screensCount === 0) recommendations.push('Consider adding sensitivity screens to potentially triggering content');

    return {
      accountId, totalMedia, withAltText: withAlt, withAutoAlt: autoAlts,
      withManualAlt: manualAlts, coveragePercentage,
      avgAltTextLength: Math.round(avgLength), sensitivityScreens: screensCount,
      contentWarnings: warningsCount, accessibilityScore, recommendations,
    };
  }

  async bulkAddAlt(entries: { mediaId: string; text: string }[]): Promise<{ success: number; failed: number; results: AltTextEntry[] }> {
    let success = 0;
    let failed = 0;
    const results: AltTextEntry[] = [];

    for (const entry of entries) {
      try {
        const result = await this.addAltText(entry.mediaId, entry.text);
        results.push(result);
        success++;
      } catch {
        failed++;
      }
    }

    return { success, failed, results };
  }
}

export const accessibilityService = new AccessibilityService();
export { AccessibilityService };
