// ============================================================================
// QuantTube API - Videos Controller
// Full video upload, processing, streaming, shorts, premieres, chapters
// ============================================================================

import type { Request, Response } from '../middleware';
import { streamingService } from '../services/streaming-service';
import { transcodingService } from '../services/transcoding-service';

interface Video {
  id: string;
  title: string;
  description: string;
  channelId: string;
  channelName: string;
  url: string;
  thumbnailUrl: string;
  duration: number;
  views: number;
  likes: number;
  dislikes: number;
  status: 'uploading' | 'processing' | 'published' | 'private' | 'unlisted' | 'scheduled';
  type: 'video' | 'short' | 'premiere';
  resolution: string;
  chapters: Chapter[];
  subtitles: Subtitle[];
  tags: string[];
  category: string;
  publishedAt: string;
  scheduledAt?: string;
  createdAt: string;
}

interface Chapter {
  id: string;
  title: string;
  startTime: number;
  endTime: number;
}

interface Subtitle {
  id: string;
  language: string;
  label: string;
  url: string;
  isAutoGenerated: boolean;
}

const videos: Map<string, Video> = new Map();
const uploadSessions: Map<string, { chunks: number; totalChunks: number; videoId: string }> = new Map();

class VideosController {
  async uploadVideo(req: Request, res: Response): Promise<void> {
    const body = req.body as any;
    const videoId = `vid_${Date.now().toString(36)}_${Math.random().toString(36).substring(2, 8)}`;

    const video: Video = {
      id: videoId,
      title: body.title || 'Untitled Video',
      description: body.description || '',
      channelId: req.user?.channelId || req.userId || '',
      channelName: req.user?.username || 'Unknown',
      url: '',
      thumbnailUrl: body.thumbnailUrl || '',
      duration: 0,
      views: 0,
      likes: 0,
      dislikes: 0,
      status: 'uploading',
      type: body.type || 'video',
      resolution: '1080p',
      chapters: [],
      subtitles: [],
      tags: body.tags || [],
      category: body.category || 'general',
      publishedAt: '',
      scheduledAt: body.scheduledAt,
      createdAt: new Date().toISOString(),
    };

    videos.set(videoId, video);

    const uploadSessionId = `upload_${Date.now().toString(36)}`;
    uploadSessions.set(uploadSessionId, { chunks: 0, totalChunks: body.totalChunks || 1, videoId });

    res.status(201).json({
      success: true,
      data: { videoId, uploadSessionId, uploadUrl: `/videos/upload/chunk?session=${uploadSessionId}`, video },
    });
  }

  async uploadChunk(req: Request, res: Response): Promise<void> {
    const sessionId = (req.query as any).session || '';
    const session = uploadSessions.get(sessionId as string);

    if (!session) {
      res.status(404).json({ success: false, error: { code: 'SESSION_NOT_FOUND', message: 'Upload session not found', statusCode: 404 } });
      return;
    }

    session.chunks++;
    const progress = session.chunks / session.totalChunks;

    if (session.chunks >= session.totalChunks) {
      const video = videos.get(session.videoId);
      if (video) {
        video.status = 'processing';
        video.url = `/streams/${video.id}/manifest.m3u8`;
        transcodingService.startTranscoding(video.id, { sourceUrl: video.url, outputFormats: ['720p', '1080p', '4k'] });
      }
      uploadSessions.delete(sessionId as string);
    }

    res.status(200).json({ success: true, data: { progress, chunksReceived: session.chunks, totalChunks: session.totalChunks, complete: session.chunks >= session.totalChunks } });
  }

  async listVideos(req: Request, res: Response): Promise<void> {
    const query = req.query as any;
    const page = parseInt(query.page || '1');
    const limit = parseInt(query.limit || '20');
    const category = query.category;
    const type = query.type;

    let filtered = Array.from(videos.values()).filter(v => v.status === 'published');
    if (category) filtered = filtered.filter(v => v.category === category);
    if (type) filtered = filtered.filter(v => v.type === type);

    filtered.sort((a, b) => b.views - a.views);
    const start = (page - 1) * limit;
    const paginated = filtered.slice(start, start + limit);

    res.status(200).json({ success: true, data: { videos: paginated, pagination: { page, limit, total: filtered.length, pages: Math.ceil(filtered.length / limit) } } });
  }

  async getTrending(req: Request, res: Response): Promise<void> {
    const trending = Array.from(videos.values())
      .filter(v => v.status === 'published')
      .sort((a, b) => {
        const scoreA = a.views * 0.4 + a.likes * 0.3 + (Date.parse(a.publishedAt) > Date.now() - 86400000 ? 1000 : 0);
        const scoreB = b.views * 0.4 + b.likes * 0.3 + (Date.parse(b.publishedAt) > Date.now() - 86400000 ? 1000 : 0);
        return scoreB - scoreA;
      })
      .slice(0, 50);

    res.status(200).json({ success: true, data: { videos: trending } });
  }

  async getShorts(req: Request, res: Response): Promise<void> {
    const shorts = Array.from(videos.values())
      .filter(v => v.type === 'short' && v.status === 'published')
      .sort((a, b) => b.views - a.views)
      .slice(0, 30);

    res.status(200).json({ success: true, data: { shorts } });
  }

  async getVideo(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    video.views++;
    res.status(200).json({ success: true, data: { video } });
  }

  async streamVideo(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }

    const quality = (req.query as any).quality || 'auto';
    const streamInfo = streamingService.getStreamUrl(video.id, quality);

    res.status(200).json({ success: true, data: { streamUrl: streamInfo.url, quality: streamInfo.quality, availableQualities: streamInfo.availableQualities, cdnNode: streamInfo.cdnNode, expiresAt: streamInfo.expiresAt } });
  }

  async getManifest(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }

    const manifest = streamingService.generateManifest(video.id, video.duration);
    res.status(200).json({ success: true, data: { manifest } });
  }

  async getChapters(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    res.status(200).json({ success: true, data: { chapters: video.chapters } });
  }

  async getSubtitles(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    res.status(200).json({ success: true, data: { subtitles: video.subtitles } });
  }

  async updateVideo(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    if (video.channelId !== req.userId && video.channelId !== req.user?.channelId) {
      res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'Not authorized', statusCode: 403 } });
      return;
    }
    const body = req.body as any;
    if (body.title) video.title = body.title;
    if (body.description) video.description = body.description;
    if (body.tags) video.tags = body.tags;
    if (body.category) video.category = body.category;
    if (body.status) video.status = body.status;
    if (body.thumbnailUrl) video.thumbnailUrl = body.thumbnailUrl;
    if (body.status === 'published' && !video.publishedAt) video.publishedAt = new Date().toISOString();

    res.status(200).json({ success: true, data: { video } });
  }

  async updateChapters(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    const body = req.body as any;
    video.chapters = (body.chapters || []).map((ch: any, i: number) => ({
      id: `ch_${i}`,
      title: ch.title,
      startTime: ch.startTime,
      endTime: ch.endTime,
    }));
    res.status(200).json({ success: true, data: { chapters: video.chapters } });
  }

  async updateSubtitles(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    const body = req.body as any;
    video.subtitles = (body.subtitles || []).map((sub: any) => ({
      id: `sub_${sub.language}`,
      language: sub.language,
      label: sub.label || sub.language,
      url: sub.url || `/subtitles/${video.id}/${sub.language}.vtt`,
      isAutoGenerated: sub.isAutoGenerated || false,
    }));
    res.status(200).json({ success: true, data: { subtitles: video.subtitles } });
  }

  async deleteVideo(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    if (video.channelId !== req.userId && video.channelId !== req.user?.channelId) {
      res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'Not authorized', statusCode: 403 } });
      return;
    }
    videos.delete(req.params.id);
    res.status(200).json({ success: true, data: { message: 'Video deleted' } });
  }

  async schedulePremiere(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    const body = req.body as any;
    video.type = 'premiere';
    video.status = 'scheduled';
    video.scheduledAt = body.scheduledAt || new Date(Date.now() + 86400000).toISOString();
    res.status(200).json({ success: true, data: { video } });
  }

  async processVideo(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    const job = transcodingService.startTranscoding(video.id, { sourceUrl: video.url, outputFormats: ['360p', '480p', '720p', '1080p', '4k'] });
    res.status(200).json({ success: true, data: { jobId: job.id, status: job.status, progress: job.progress } });
  }

  async getVideoAnalytics(req: Request, res: Response): Promise<void> {
    const video = videos.get(req.params.id);
    if (!video) {
      res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Video not found', statusCode: 404 } });
      return;
    }
    res.status(200).json({
      success: true,
      data: {
        videoId: video.id,
        views: video.views,
        likes: video.likes,
        dislikes: video.dislikes,
        avgWatchTime: video.duration * 0.65,
        retentionRate: 0.72,
        clickThroughRate: 0.045,
        impressions: video.views * 3,
        demographics: { '18-24': 0.35, '25-34': 0.28, '35-44': 0.18, '45+': 0.19 },
        traffic: { search: 0.4, recommended: 0.35, external: 0.15, direct: 0.1 },
      },
    });
  }
}

export const videosController = new VideosController();
